name: CI Workflow

trigger:
  type: commit
  branch:
    pattern: main

actions:
  - name: Build, Test, and Archive iOS
    run:
      - xcodebuild test
        -scheme "Rhizome"
        -destination "platform=iOS Simulator,name=iPhone 15"
        -skipPackagePluginValidation YES
      - xcodebuild archive
        -scheme "Rhizome"
        -destination "generic/platform=iOS"
        -archivePath $HOME/DerivedData/Rhizome-iOS.xcarchive
    artifact_paths:
      - "**/Logs/Test/*.xcresult"
      - "$HOME/DerivedData/Rhizome-iOS.xcarchive"

  - name: Build, Test, and Archive macOS
    run:
      - xcodebuild test
        -scheme "Rhizome"
        -destination "platform=macOS"
        -skipPackagePluginValidation YES
      - xcodebuild archive
        -scheme "Rhizome"
        -destination "platform=macOS"
        -archivePath $HOME/DerivedData/Rhizome-macOS.xcarchive
    artifact_paths:
      - "**/Logs/Test/*.xcresult"
      - "$HOME/DerivedData/Rhizome-macOS.xcarchive"

  - name: Build, Test, and Archive watchOS
    run:
      - xcodebuild test
        -scheme "Rhizome"
        -destination "platform=watchOS Simulator,name=Apple Watch Series 9 (45mm)"
        -skipPackagePluginValidation YES
      - xcodebuild archive
        -scheme "Rhizome"
        -destination "generic/platform=watchOS"
        -archivePath $HOME/DerivedData/Rhizome-watchOS.xcarchive
    artifact_paths:
      - "**/Logs/Test/*.xcresult"
      - "$HOME/DerivedData/Rhizome-watchOS.xcarchive"

  - name: Build, Test, and Archive visionOS
    run:
      - xcodebuild test
        -scheme "Rhizome"
        -destination "platform=visionOS Simulator,name=Apple Vision Pro"
        -skipPackagePluginValidation YES
      - xcodebuild archive
        -scheme "Rhizome"
        -destination "generic/platform=visionOS"
        -archivePath $HOME/DerivedData/Rhizome-visionOS.xcarchive
    artifact_paths:
      - "**/Logs/Test/*.xcresult"
      - "$HOME/DerivedData/Rhizome-visionOS.xcarchive"

notifications:
  on_failure:
    - type: email
      recipients:
        - david@jensenius.com
